version: '3'
services:
  my-project:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
